language: go
go:
- "1.10"
cache:
  directories:
  - vendor
install:
- go get -u github.com/hashicorp/{go-plugin,go-hclog}
- go get -u golang.org/x/net/{context,http2,trace}
- go get -u github.com/golang/dep/cmd/dep
- dep ensure -v
script:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10
- golangci-lint run --disable=errcheck,megacheck --enable=goimports,goconst,gocyclo
  #- ./codecov.sh
  #- go test ./tests -tags=integration
