language: go
go:
- 1.10
cache:
  directories:
  - vendor
install:
- go get -u github.com/hashicorp/{go-plugin,go-hclog}
- go get -u golang.org/x/net/{context,http2,trace}
- go get -u github.com/golang/dep/cmd/dep
- dep ensure -v
script:
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install --force
- gometalinter --vendor --fast --disable=gotype --disable=vetshadow --disable=gas --skip=mock ./...
- ./codecov.sh
- go test ./tests -tags=integration
